### ISSUE TITLE
Remove RFNs

### ISSUE THREAD

**Issue by davelab6** [fontnerd/TypeTalk-Fonts#1]
Please don't use RFNs on Github, it makes the typical github fork-modify-pullrequest flow break the license (to avoid it they must first rename the fonts before making modifications, and then you rename them back); it also means web font users who subset the fonts or convert them to all formats break the license (modulo renaming.)

**Comment by fontnerd** [comment]
Thanks, David. Will try to change soon, I'm a "Gitidiot"!

Amy

**Comment by davelab6** [comment]
You can just hit the green button on https://github.com/fontnerd/TypeTalk-Fonts/pull/3 :)
